### ISSUE TITLE
application failed to send message to finder extension

### ISSUE THREAD

**Issue by kcorey** [milke/GitFinder-Issues#54] opened 2020-03-15 09:27 UTC
I wonder if this problem has actually been fixed?
https://github.com/milke/GitFinder-Issues/issues/43

The comment at the end says there's a "huge" new update to version 1.3 that will handle this "more graciously".

I'm on Catalina 10.15.3, GitFinder 1.4.1, and I'm still running into this.

At the very least, the GitFinderSync process should have its own icon in the title bar allowing for easy quitting.  The next best would be to realise when GitFinder itself has died, and then GitFinderSync should die.

As it is, when it's unhappy, it can crater my i9-8 core mac.

**Comment by kcorey** [comment] 2020-03-15 10:19
Wow, this just makes the app unusable.

Again, got the error message above, GitFinder closed, cpu maxed out by GitFinderSync.

**Comment by milke** [comment] 2020-03-15 10:36
> I wonder if this problem has actually been fixed? #43

I'll respond there. I'd appreciate reopening closed related issues (if you've already found it), than opening a new one.

**Comment by milke** [comment] 2020-03-15 10:37
Duplicate of #43

**Comment by milke** [comment] 2020-03-15 10:37
Duplicate of #43

**Comment by milke** [comment] 2020-03-15 10:38
Duplicate of #43

**Closed by milke** 2020-03-15 10:38 UTC

**Comment by milke** [comment] 2020-03-15 14:04
@kcorey, I don't know if you got notified, as you're still not a participant in that issue, so please make sure to read my answer in #43 and continue the discussion there, if needed.
