### ISSUE TITLE
lots of errors when deleting the local working directory

### ISSUE THREAD

**Issue by azankl** [milke/GitFinder-Issues#60] opened 2020-09-22 04:27 UTC
I deleted a local repo by simply deleting it in Finder. That created a flurry of error messages from GitFinder, like the 2 listed below. Is it wrong to delete a repo in Finder?
<img width="416" alt="Screen Shot 2020-09-22 at 2 15 11 pm" src="https://user-images.githubusercontent.com/4812335/93844148-8bb4a600-fcdf-11ea-86ce-3f891d18a36b.png">
<img width="419" alt="Screen Shot 2020-09-22 at 2 14 42 pm" src="https://user-images.githubusercontent.com/4812335/93844153-8f482d00-fcdf-11ea-9912-12475903c028.png">

**Comment by milke** [comment] 2020-09-25 07:52
@azankl, no operation in Finder can be wrong 🙂

I can't seem to be able to reproduce this error with the latest version of GitFinder (1.5.1). Is that the version you use? Also, can you clarify whether you only trashed that local repo (hence the folder is only moved to the Trash), or you actually deleted it (by emptying the Trash, in which the repo was already)?

I couldn't reproduce it behaviour neither by trashing a repo, nor by emptying the Trash (where the trashed repo was already) nor by doing `rm -rf` on the repo from the terminal. So I'd appreciate if you an outline all steps you do when you encounter this error.

**Comment by azankl** [comment] 2020-09-27 04:33
I tried to reproduce the problem:
I deleted the 'Ontoclick' repo I had previously cloned from Github by selecting the Ontoclick folder in Finder and selecting the Trash icon in the Finder Window Toolbar. That created the following error:
<img width="532" alt="Screen Shot 2020-09-27 at 2 17 31 pm" src="https://user-images.githubusercontent.com/4812335/94356086-a915b580-00cd-11eb-809e-5f7bf6aeb924.png">
I then tried to clone the repo again by selecting the parent folder and choosing 'Clone' from the Gitfinder contextual menu and choosing 'Ontoclick' from my available repos on Github. Gitfinder starts cloning but gets stuck at "Validating". The Validation never finishes, so I had Force Quit Gitfinder. I then tried cloning the repo again, as described above, and this is when I get the flurry of error messages described in my first post. I guess force quitting Gitfinder did not help, but why does Gitfinder get stuck on 'Validating'?

**Comment by luxlogica** [comment] 2020-11-14 00:37
This problem still seems to be happening on MacOS Big Sur. I've just moved/deleted some old repository folders, and got a handful of messages like this:

<img width="278" alt="Screen Shot 2020-11-14 at 11 05 12 am" src="https://user-images.githubusercontent.com/2994472/99133356-bed73e00-266d-11eb-948b-0729dffd5718.png">

**Comment by milke** [comment] 2020-11-24 18:11
I've just uploaded **1.6.1b1**, you can update your current copy to it by checking for the **Beta** channel in the update preferences. Check it out and let me know if you see similar message reported again.

**Comment by milke** [comment] 2020-12-01 12:18
Okay, I consider this fixed (the fix is now in the official release **1.6.1**), so I'm closing this. If the issue reappears, feel free to reopen.

**Closed by milke** 2020-12-01 12:18 UTC
Labels: bug
