### ISSUE TITLE
Putting GitFinder extension at the top does not make icons visible in Finder when using Resilio Sync

### ISSUE THREAD

**Issue by jafish** [milke/GitFinder-Issues#24] opened 2018-02-17 03:30 UTC
In the section of GitFinder's support article titled "GitFinder is running, but I don't see icon badges nor git menu commands?", it suggests putting GitFinder at the top of the list in "System Preferences->Extensions->Finder". I tried this, with my only other Finder extension being Resilio Sync, but the GitFinder icons still don't show up. They only show up if I disable the Resilio Sync extension entirely, but the support article suggests that this isn't necessary.

**Comment by milke** [comment] 2018-02-17 14:23
Are both GitFinder and Resilio Sync set to start at login/system start-up?

**Comment by jafish** [comment] 2018-02-17 14:59
Yes. I forgot to mention in my report that the contextual menus DO work, just not the icons.

**Comment by milke** [comment] 2018-02-17 22:29
> Yes. I forgot to mention in my report that the contextual menus DO work, just not the icons.

I understand that.

The suggestion you quoted from support/FAQ is actually an official advice from Apple. But I wouldn't be the first time they gave the wrong one. They also didn't do very good job in providing a way to avoid extension collision. I tried this advice with Dropbox extension (the only other one I use) and it worked every time, but now I don't know if that was just a happy coincidence.

What's actually bad in this situation is that there isn't really anything I can do to improve this :-(. It's not controlled from the application nor extension, it's completely up to the system. Even setting Resilio Sync not to start at login/system start-up won't necessarily solve the issue, as the extension would still be started by the OS, regardless of the containing application.

I filled a bug report about this long time ago and it was marked as a duplicate. I suggest you do it too. If more people do it, perhaps will Apple finally do something about it. In the meanwhile, I'll investigate further if there's anything I can do, but I can't promise anything.

**Comment by jafish** [comment] 2018-02-19 03:13
Thanks for the detailed reply. I'll assume that any extension that I want to be able to see icons for needs to be the only one enabled.

**Comment by milke** [comment] 2018-02-20 11:17
Not exactly, you can have more extensions enabled, but they mustn't "monitor" the same folder. As far as I can see, Resilio Sync default sync folder is *"~/Resilio Sync"*, so it monitors that one for sure. It also asks for the downloads folder (the default being *"~/Downloads"*), so I assume it monitors that one as well. As long as GitFinder doesn't monitor those folders, you'll see its icon badges.

If you're interested in more details, which perhaps may help you to deal with this issue easier, read further, I played with different extensions myself and here are my findings…

First of all, I can't find that document on Apple support page, saying that the priorities of Finder extensions are determined by they order in the extensions list. And that seems to be wrong anyway. From my experience playing with three Finder extensions (and their applications, those are **GitFinder**, **Dropbox** and **Resilio Sync**) past two days, if more extensions monitor the same folder, the one started first will show its icon badges, the others cannot. The problem is one can't tell which one will be started first and it's not deterministic anyway.

Finder extensions are started by the OS, not by the containing applications. They are started at login, but also additional extension processes can be started every time **open** and **save** panels are shown in ANY application, as well as with some other system events and probably even Apple themselves don't know when exactly extension processes are spawned. The most annoying thing may be that Finder extensions (in GitFinder's case it's process called **GitFinderSync**) are started even if the containing applications (in GitFinder's case it's process called **GitFinder**) aren't running! Perhaps that is desired behaviour, but I see it as wrong.

I tried to implement "a proper" behaviour in GitFinder as much as possible. If **GitFinderSync** extension is started by the OS, it will wait for about 2-3 seconds and then it will check if the containing application **GitFinder** is also running. If it is not, the extension will terminate itself. Then, when the containing application **GitFinder** is started, it will "force" (I can go into details on how it's done, but let's leave it out of this explanation for now) the OS to start the **GitFinderSync** extension as well. Finally, if the containing application **GitFinder** is terminated, during termination process it will send a signal to the **GitFinderSync** extension to terminate as well. This ensures that the extension and its containing application are either BOTH running, or BOTH not running.

Other extension don't necessarily behave the same. You can see it yourself; quit **Resilio Sync** and try to trash it and you'll probably get a warning as: `The item “Resilio Sync” can’t be moved to the Trash because some of its extensions are in use.` But even if all other extensions and their containing applications behaved "the proper" way, it wouldn't necessarily determine the order in which they are started, hence which one would show icon badges in folders monitored by more extensions.

It's clear Apple didn't do a very good job in resolving Finder extension collisions when it comes to icon badges. I filled a bug request about it long time ago (2 years or so) and it was marked as a duplicate. But still, nothing has been done about it two major OS releases later :-(

I'm sorry you've got this problem, but as you can see from the above written, there's not much more I can do form what I've already done. Your best bet not to get icon badges collisions is to avoid more extensions monitoring the same folder. Yeah, I know you probably want to sync your repositories with Resilio servers, but I can't give you any better answer.

**Closed** 2019-08-02 10:24 UTC
Labels: question
