### ISSUE TITLE
Reverting a file from the commit dialog causes crash

### ISSUE THREAD

**Issue by grahamegrieve** [milke/GitFinder-Issues#111] opened 2022-02-12 22:07 UTC
I choose commit. I see a file I don't want the changes for, and revert it. Immediately, the dialog disappears, and I can nothing more on the repository (all options greyed out) until I quite and restart gitfinder (and even that sometimes I have to wait a few minutes for something to happen). Then I get all my menu options back.

**Comment by milke** [comment] 2022-02-15 14:09
@grahamegrieve, can you please be more specific what you mean by "_revert it_"? I tried to reproduce this, but without success, probably because I don't do exactly the same steps as you do. I know it's maybe tedious, but it'd be very helpful if you could post a short video of what you do when the crash happens. Thanks a lot.

On a related note, is this reproducible? Can you cause the crash every time you do the same actions?

**Comment by grahamegrieve** [comment] 2022-02-16 01:31
https://user-images.githubusercontent.com/5858581/154179097-97fa7944-1e14-43ee-91a1-4ba06208b783.mov

**Comment by grahamegrieve** [comment] 2022-02-16 01:31
this happens every time I revert

**Comment by milke** [comment] 2022-03-06 15:16
@grahamegrieve, that files list (in the commit action window) wasn't really meant to show any contextual menu, since it screws the modal status of the application, but it slipped my attention. However, since you use it, I assume other people may find it handy, so I decided to leave it there and fix the problem. It wasn't really a crash, rather GitFinder got confused if a modal action window for the repository was shown and hence disabled all further actions, when it shouldn't.

This is fixed now in the latest beta version **1.7.5b2 (build 120)**. You can download the lates beta [**here**](https://get.gitfinder.com/GitFinder_beta.dmg), but you can also update your current copy using in-app updater. Just make sure to check for the **Beta** release channel in the update preferences, like in the picture below.
<img width="495" alt="Screen Shot 2022-03-06 at 15 43 47" src="https://user-images.githubusercontent.com/291305/156929325-d4e2e420-8d69-405d-bf67-aaa70aece785.png">

Let me know how it all works.

**Closed** 2022-03-06 22:24 UTC
Labels: bug
