### ISSUE TITLE
Finder icons not working in macOS 11.5.2

### ISSUE THREAD

**Issue by eerkov** [milke/GitFinder-Issues#97] opened 2021-08-23 07:04 UTC
Since the update to 11.5.2 (as far as I can tell) I no longer see GitFinder's Finder icons.

I've removed and re-added repos, enabled/disabled the extension, restarted the Finder and GitFinder, but to no avail.
The context menu does work on items inside a repo, although there's one repo that isn't recognized at all (may be a separate issue).

Edit: another repo that I'm sure of worked before now also does not allow the contextual menus anymore (it did 5 minues ago).

**Comment by milke** [comment] 2021-08-23 13:00
@eerkov, before I start digging into this, one question… When you can't see any contextual menu item or Finder icon badges while GitFinder is running, do you see a process named **GitFinderSync** running? Like in the picture below:
<img width="852" alt="Screenshot 2021-08-23 at 14 59 18" src="https://user-images.githubusercontent.com/291305/130451330-d7a05faf-0925-48da-8cdf-6b30bf648652.png">

**Comment by eerkov** [comment] 2021-08-23 13:38
I've got lots of those:

![Schermafbeelding 2021-08-23 om 15 36 16](https://user-images.githubusercontent.com/6352454/130456737-140bfcf3-14c2-4aa0-9f26-f60613a10f92.png)

The icons are not showing up anywhere. For some repos, the context menu is showing as usual, for others it's only partly there:

<img width="270" alt="Schermafbeelding 2021-08-23 om 15 35 15" src="https://user-images.githubusercontent.com/6352454/130456854-b8cc879a-a4ff-452e-a746-52733f22344d.png">

This is while selecting a file I know is in the repo and has changes.

**Comment by milke** [comment] 2021-08-23 13:55
Okay, let's first tackle missing icon badges… It may happen that macOS update screwed order of Finder Sync extension registration, so more extensions are monitoring the same folders and showing icon badges causes collisions.

Please go to [**Support**](https://gitfinder.com/support) page, then under **FAQ** find **GitFinder is running, but I don't see icon badges nor git menu commands?** It's rather long, because it covers all possible scenarios of icon badges and contextual menus not showing, but you're interested in eventual extension collision, the paragraph of interest starts with:

>If everything above is fine, and you still don't see icon badges (but you do see git menu commands), GitFinder extension may be colliding with other Finder extensions.

Follow the instructions outlined there and let me know if that work for at least showing icon badges in repositories with fully shown contextual menu (_"as usual"_, as you've said).

**Comment by milke** [comment] 2021-08-24 16:24
@eerkov, I would still suggest you to do what I mentioned in my previous post and described on the [**support**](https://gitfinder.com/support) page. That way you'd be able to use both extensions, it's just important to register **GitFInderSync** first. For your convenience, I'll repeat it here:

> … and you still don't see icon badges (but you do see git menu commands), GitFinder extension may be colliding with other Finder extensions. This happens if your git repository folder is monitored by multiple Finder extensions. In such case, please make sure GitFinderSync extension is "registered first". The easiest way to ensure this is to go to **System Preferences > Extensions > Finder Extensions** and uncheck/unregister all extensions except **GitFinderSync**, like it the picture below:

![extension_l](https://user-images.githubusercontent.com/291305/130653402-22ffe581-3d5a-41ea-b417-dcdc980aeb60.png)

> Then relaunch GitFinder and make sure the icon badges are present. Then register/check back all extensions you unregistered previously. After this procedure, you should always see GitFinder icon badges, provided GitFinder is running and a particular current folder in monitored. This procedure needs to be repeated every time you get Finder extensions collision, but doing it just once should suffice. This is all due to a bit sloppy job Apple did regarding more extensions monitoring the same folders and there's nothing we can do about it.

Like said, the problem isn't related to any specific Finder Sync extension, and unfortunately I can't do anything about it. I only didn't know that once set correctly, an OS update may screw things back again 🙁

**Comment by eerkov** [comment] 2021-08-25 07:08
I dit this, and hope it will remain after each restart (which doesn't happen often). 
In my case, I think the DeepL Finder extension was new, so it might have been just the first restart after installation when the problem occurred, and hopefully it now doesn't occur again.

**Comment by eerkov** [comment] 2021-08-25 07:08
Thanks for your help!

**Comment by milke** [comment] 2021-08-25 08:51
> I dit this, and hope it will remain after each restart (which doesn't happen often).

As far as I tried and tested, effects of the outlined procedure survive restarts. But apparently, OS update can screw it up. Hopefully not every time. If this happens again, you know what to do. It's frustrating I can't do anything about it 🙁

I'm closing this now, but if the issue appears again and provided fix doesn't work anymore, feel free to reopen it.

**Closed by milke** 2021-08-25 08:51 UTC
Labels: question
