### ISSUE TITLE
Fail to merge - cannot stash changes - there is nothing to stash.

### ISSUE THREAD

**Issue by twodayslate** [milke/GitFinder-Issues#22] opened 2018-02-16 02:59 UTC
I am trying to merge a local branch with a remote branch and I cannot since GitFinder thinks I have uncommitted changes. 
```
twodayslate@Zacharys-MBP tothecore (twodayslate) $ git status
On branch twodayslate
Your branch is up-to-date with 'origin/twodayslate'.

Untracked files:
  (use "git add <file>..." to include in what will be committed)

	Pods/BugfenderSDK/
	Pods/Target Support Files/BugfenderSDK/
	support/

nothing added to commit but untracked files present (use "git add" to track)

```
<img width="612" alt="screen shot 2018-02-15 at 21 57 09" src="https://user-images.githubusercontent.com/1085707/36291802-38db46d6-129b-11e8-96b4-526706ca2641.png">
<img width="612" alt="screen shot 2018-02-15 at 21 57 15" src="https://user-images.githubusercontent.com/1085707/36291801-38cd7f74-129b-11e8-95d6-76abbec8a114.png">
<img width="612" alt="screen shot 2018-02-15 at 21 57 18" src="https://user-images.githubusercontent.com/1085707/36291800-38bb3012-129b-11e8-9356-c94fd3e1b651.png">
<img width="532" alt="screen shot 2018-02-15 at 21 57 21" src="https://user-images.githubusercontent.com/1085707/36291799-38ae6864-129b-11e8-80da-5fe3516252b3.png">

**Comment by milke** [comment] 2018-02-16 10:03
Yes, it's a bug. GitFinder is confused by untracked files (which you've probably just added to a folder in a repository) and regards them as uncommitted changes.

I'll fix it in the next update. In the meanwhile, if this happens again, when the action panel turns into **Uncommitted Local Changes**, just go ahead and click the **Merge** button in the middle, it should work.

**Comment by twodayslate** [comment] 2018-03-02 17:48
What is the expected time of release for this fix?

**Comment by milke** [comment] 2018-03-06 22:59
@twodayslate, I'm currently busy with some other things related to GitFinder (unfortunately, not directly coding/fixing/implementing). I'm also collecting some input about some other issues that I want fixed in the first upcoming (fix) update 1.0.1. I expect it to go out around March 20, possibly even earlier.
In the meanwhile, as a workaround just click the **Merge** button in the middle, it should work. Thanks for you patience and understanding.

**Comment by milke** [comment] 2018-03-16 17:15
@twodayslate, the fix for this issue is available in the latest GitFinder beta version **1.0.1b2 (build 35)**. You can update your current copy to this beta if you choose **Beta** as the **Release channel** in the GitFinder's **Update** preferences. Or you can download it directly [here](https://zigz.ag/GitFinder/updates/GitFinder_beta.dmg).

There are still a few more things I'd like to fix before releasing **1.0.1** officially (in about a week), but I'd really appreciate if you try the latest beta and confirm the problem has been fixed. Thanks in advance.

**Comment by twodayslate** [comment] 2018-03-21 00:15
Thanks! Worked as expected. 

If I hit merge instead of stash when there are actually uncommitted changes (the merge fails), the error message is not very clear. 

<img width="532" alt="screen shot 2018-03-20 at 20 12 22" src="https://user-images.githubusercontent.com/1085707/37689394-0ede35a6-2c7b-11e8-99a0-da28fbe4ab75.png">

It should tell you how to fix things for the merge, or that the merge was not successful and nothing was actually merged. Example:

> Merge failed! 3 uncommitted changes would be overwritten by the merge. Commit or stash your changes before merging again.

**Comment by milke** [comment] 2018-03-22 16:23
Good to know the issue is fixed. I'll release an official version **1.0.1** next Monday or Tuesday.

Most (99%) of git related errors you see coming from GitFinder are just passed from the underlying [libgit2](https://libgit2.github.com) library. You are completely right many (if not all) of them should be clearer. But the thing is, there are a lot of them. Also, error code doesn't necessarily match error description; there can be many different descriptions (reasons/causes) for errors with the same error code.

My intention is to scan the whole libgit2 code for error description (unfortunately, those strings are not defined in one file, but are hardcoded in the same place where particular error is defined) and make conversion table from libgit2 error description to much clearer GitFinder description. But it's a lot of work, and it probably won't happen in the next couple of updates of GitFinder.

Thanks for your suggestion though.

**Closed** 2018-07-24 16:51 UTC
Labels: bug
