### ISSUE TITLE
[ WISHLIST ] Quality-of-life improvements

### ISSUE THREAD

**Issue by cig0** [milke/GitFinder-Issues#44] opened 2019-05-18 13:31 UTC
Hi,

I finally have the time to properly evaluate GitFinder as a companion to my workflow (command-line + VSCode), and I'm surprised I like it a lot, like "this could be _one of those tools_" -- that you end up using all the time without ever actively looking to do so.

That's great, says a lot about it.

That's why I compiled the following list with what I consider quality of life improvements that I want to share with you, and if possible know your thoughts about it:

~1. When adding new repositories, **please** **please** **please** add an optional _recursive_ functionality.
I have plenty of repos, some of them sorted hieratically in a folder tree (like "personal" and "work"), and having to add them to GitFinder by hand, one by one, is a real pain -- but moreover I know that in the long run it could be a _potential_ deal-breaker for me.
I understand that a feature like this could potentially slow down GitFinder startup: maybe some sort of validation using a list or map to learn what repos are gone and what are the new additions, if any, could be implemented. Maybe I'm talking total nonsense and there's a far better way to do it :)~

**I just tried this out of curiosity and the functionality is already there, woo-hoo!** 🍩

2. Please consider adding a new service to Finder in order to quickly be able to add a folder (repo) - or a group of folders.

3. While the option "Show Dock icon: **Never**" is selected (and "Show menu bar icon" is enabled), GitFinder's icon still pops-up in the Dock whenever a new GitFinder window is opened. Restarting GitFinder doesn't works.

Otherwise that I'm having a smooth sailing so far.

_My sys specs_
GitFinder: 1.3b3 (52)
macOS: 10.14.5

The only other extension I added to Finder is ExpanDrive.

Thanks!

**Comment by milke** [comment] 2019-05-24 22:08
Hi there!

> 2. Please consider adding a new service to Finder in order to quickly be able to add a folder (repo) - or a group of folders.

I'm afraid, due to sandboxing restrictions, this isn't possible. In order to gain access to repo folders, they must be selected using an open-file-selector, of dragged into the list of folders from Finder or some other file manager which supports URL drags. Those are the ways implemented in GItFinder preferences window.

> 3. While the option "Show Dock icon: Never" is selected (and "Show menu bar icon" is enabled), GitFinder's icon still pops-up in the Dock whenever a new GitFinder window is opened. Restarting GitFinder doesn't works.

This certainly sounds like a bug, but I can't reproduce it. Can you reproduce it every time with any GitFinder window (Preferences, License, Repo Browser, Show Changes…)?

Since you're using 1.3b3… Do you work with Git-LFS enabled repositories? If so, do you use GitFinder on them? Have you had any issues regarding that functionality?

Thank you!!

**Comment by cig0** [comment] 2019-05-27 14:43
Hi @milke, thanks for the quick reply!

> While the option "Show Dock icon: Never" is selected (and "Show menu bar icon" is enabled), GitFinder's icon still pops-up in the Dock whenever a new GitFinder window is opened. Restarting GitFinder doesn't works.
I see that GitFinder's Dock icon shows up when opening a window, i.e. Blame, History, Compare, etc.
If this is the expected behavior, then sorry for the noise!

> Since you're using 1.3b3… Do you work with Git-LFS enabled repositories? If so, do you use GitFinder on them? Have you had any issues regarding that functionality?
No I'm not...

Thanks!

**Comment by milke** [comment] 2019-05-27 18:27
Hi @cig0,

> I see that GitFinder's Dock icon shows up when opening a window, i.e. Blame, History, Compare, etc.
If this is the expected behavior, then sorry for the noise!

No, if your settings is "Show Dock icon: Never", then the GitFinder's icon should not appear in the Dock ever, regardless of any window. Since I can't reproduce it, I can make a special build for you with some additional logging. From the additional logging info I should be able to figure out what the problem is. Let me know if you're willing to help me with it.

> No I'm not...

Just for clarification; you don't work with Git-LFS enabled repositories, or you do but you don't have any problem with GitFinder handling those repositories?

**Comment by cig0** [comment] 2019-05-27 21:30
> No, if your settings is "Show Dock icon: Never", then the GitFinder's icon should not appear in the Dock ever, regardless of any window. Since I can't reproduce it, I can make a special build for you with some additional logging. From the additional logging info I should be able to figure out what the problem is. Let me know if you're willing to help me with it.

By all means. I made a quick screencast to show you what happens on my side: https://drive.google.com/file/d/1FGLT5--IpHKdnhM1qGUuZTLNvQbcvBuO/view

> Just for clarification; you don't work with Git-LFS enabled repositories, or you do but you don't have any problem with GitFinder handling those repositories?

Sorry about that; no, I'm not using Git-LFS right now nor I have any LFS-enabled Git repository.

**Comment by milke** [comment] 2019-05-28 13:02
> By all means. I made a quick screencast to show you what happens on my side:

Watching your video, I managed to reproduce it. It seems there is an issue syncing application preferences and its activation policy (meaning, whether it shows the Dock icon and menu bar or not). I'll fix it in the next update.

> no, I'm not using Git-LFS right now nor I have any LFS-enabled Git repository.

Thanks for clarification.

**Comment by cig0** [comment] 2019-05-30 02:58
Nice. Should I be on beta or stable channel to receive the update?

**Comment by milke** [comment] 2019-05-30 14:24
It will appear in the beta channel first. I still need to finish some Git-LFS related stuff before rolling out 1.3 officially.

**Comment by milke** [comment] 2019-07-28 12:26
Hey @cig0, I fixed this in version 1.3b5 (the current beta is 1.3b6). I'm not able to reproduce it anymore. Can you please confirm this?

**Comment by cig0** [comment] 2019-07-28 19:09
On it

**Comment by milke** [comment] 2019-08-02 10:11
@cig0, I'm closing this. If you reproduce it again, feel free to reopen.

**Closed by milke** 2019-08-02 10:11 UTC
Labels: bug
