### ISSUE TITLE
GitFinder keeps asking me for my username

### ISSUE THREAD

**Issue by majorproblem** [milke/GitFinder-Issues#39] opened 2018-07-10 12:53 UTC
I have recently taken up git and use GitFinder for my interaction. What I don't understand is why GitFinder asks me for my username when I do "commit and push" -- I can understand that it wants to know it the first time it connects to the server but for every subsequent call after that seems a bit odd. It finds my ssh-key alright afterwards, it is just the username that seems to be gone all the time.

Am I just daft and missing something obvious?

**Comment by milke** [comment] 2018-07-24 16:39
Hey @majorproblem,

I really, really apologise for this very delayed response, it happened for two reasons: firstly, I was on a (sort of "no-connection") vacation for about 10 days, without any access to Internet or any other online service. Secondly, it took me two days to reproduce your issue and I think I finally got it. Before fixing it, I just want to confirm your configuration and that the problem is actually the same. So here are some questions:

1. Does it happen only when pushing changes to a remote, or it also happens when fetching/pulling changes from the remote?

2. What are "Fetch URL" and "Push URL" shown for the remote you're pushing to (see image below)?

![settings](https://user-images.githubusercontent.com/291305/43153072-92ee24a2-8f70-11e8-86bc-78cc000a0bee.png)

Once I get your answers I may have some additional questions. Once again, sorry about the delay.

**Comment by milke** [comment] 2018-07-26 21:35
Even though I haven't received any response from you @majorproblem, I think I identified what the problem was. It probably happens because you have _.git-credentials_ file containing wrong password for a given domain/host. That would cause accidental deletion of already saved HTTPS credentials from the keychain and the next time you want to push GitFinder would ask you for a username/password again.

I fixed this in the latest beta of GitFinder, version **1.0.2b1 (build 37)**. You can update to it from GitFinder update preferences, just choose **Beta** release channel, like in the picture below:
![update_prefs](https://user-images.githubusercontent.com/291305/43289790-555fee3c-912c-11e8-86d7-898e01a09651.png)
Please try this beta and let me know if it fixes your problem.

**Comment by majorproblem** [comment] 2018-07-29 01:47
My turn to apologise: I am currently on a three week road trip in Canada and can not check on this problem until I am back by the middle of August. Sorry about this.

**Comment by milke** [comment] 2018-07-30 20:30
@majorproblem, no problem. I'll release it officially in 3-4 days anyway, because it fixes that problem with invalid credentials in _.git-credentials_ file. It may not be your problem though, so please check it out once you're back. I'd like to hear about results of your test in any case (success or not). Thanks.

**Comment by milke** [comment] 2018-08-02 18:30
I've just made the fix officially available in version 1.0.2. Hence, I'll close the issue. @majorproblem, if it doesn't work for you, feel free to reopen and let me know.

**Closed by milke** 2018-08-02 18:30 UTC
Labels: bug
